services:

  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD:  fireballs
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql